version: '3'

services:
  backend:
    build: ../backend
    environment:
      - OPENAI_KEY=123
      - OPENAI_MODEL=123
    ports:
      - "8000:8000"

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
    - backend

